### ISSUE TITLE
昨晚的版本CD2模式有问题

### ISSUE THREAD

**Issue by J666Z** [shenxianmq/Auto_Symlink#12]
地址并没有加http:，但是里面加了static/http/http://，拉2.1.1的版本就没有问题，那个版本稍微好点，我只需要元数据和strm，字幕不需要
另外，我全部同步，我是小雅挂到CD54的webdav下面，下载模式会经常是失败，复制模式会可能只有文件，没有内容

**Comment by shenxianmq** [comment]
问题描述不清

**Comment by J666Z** [comment]
昨晚最新版本，云端地址没有加http 但是strm文件打开看了，*****static/http/http://***，之前是直接static/http/ip地址

**Comment by J666Z** [comment]
另外同步异常
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/autosync/MetadataCopyer.py", line 67, in copy_metadata
    self.save_metadata(source_file, target_file)
  File "/app/autosync/MetadataCopyer.py", line 99, in save_metadata
    shutil.copy2(source_file, target_file)
  File "/usr/local/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^

**Comment by shenxianmq** [comment]
已修复
