### ISSUE TITLE
复制元数据报错，但是实际是可以下载的到本地的

### ISSUE THREAD

**Issue by whistle003** [shenxianmq/Auto_Symlink#41]
2024-04-29 11:07:13,239 - INFO - 元数据复制出错::: /home/115/Emby/Tomato_nt/shorts/一树梨花压海棠 (2024)/season01-poster.jpg => [Errno 22] Invalid argument

2024-04-29 11:07:13,239 - INFO - Traceback (most recent call last):
  File "/app/autosync/MetadataCopyer.py", line 74, in copy_metadata
    self.save_metadata(source_file, target_file)
  File "/app/autosync/MetadataCopyer.py", line 108, in save_metadata
    shutil.copy2(source_file, target_file)
  File "/usr/local/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 279, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/local/lib/python3.11/shutil.py", line 197, in copyfileobj
  
  
  docker部署，网盘是115，使用cd2挂载进行同步的

**Comment by shenxianmq** [comment]
报这个错误说明这个元数据大概率是损坏/文件名中有非法字符
