### ISSUE TITLE
日志中循环不断出现这日志是为啥？

### ISSUE THREAD

**Issue by EndBoy520** [shenxianmq/Auto_Symlink#56]
```shell
#As Bot# ::: Telegram Bot功能未启动,如需启动,请到常用工具中的通知工打启动通知
INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8095 (Press CTRL+C to quit)
#As Bot# ::: Telegram Bot功能未启动,如需启动,请到常用工具中的通知工打启动通知
INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8095 (Press CTRL+C to quit)
#As Bot# ::: Telegram Bot功能未启动,如需启动,请到常用工具中的通知工打启动通知
INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8095 (Press CTRL+C to quit)
```

**Comment by EndBoy520** [comment]
中间偶尔出现了一个这个。这个是停止后重启出现的。之前看见这个docker一直处于重启中，出现异常，看日志，几千行如上的重复日志，只得停止然后启动，成功启动还是会输出这样的日志，不知为何。tg通知我也没用它，以前里面只有建立strm的日志，没其他任何东西啊。
```shell
Traceback (most recent call last):
  File "/mnt/shenxian/Auto_Symlink_Web/AsBot.py", line 400, in <module>
  File "/mnt/shenxian/Auto_Symlink_Web/utils/commons.py", line 20, in _singleton
  File "/mnt/shenxian/Auto_Symlink_Web/AsBot.py", line 104, in __init__
AttributeError: 'NoneType' object has no attribute 'get'
``` 

```yml
version: "3"
services:
    auto_symlink:
        container_name: auto_symlink
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - /clouddrive2/CloudNAS:/clouddrive2/CloudNAS:rslave
            - /home/mmcblk0/auto_symlink/Media:/Media
            - /opt/docker-data/auto_symlink/config:/app/config
        ports:
            - 8098:8095
        restart: always
        network_mode: "1panel-network"
        logging:
            options:
                max-size: 10m
                max-file: 3
        image: shenxianmq/auto_symlink:latest
```
